# Generated by Django 5.2.5 on 2025-11-21 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("estabelecimentos", "0005_alter_estabelecimento_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="FotosEspaco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foto", models.ImageField(blank=True, upload_to="Fotos_Espaco/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "estabelecimento",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estabelecimentos.estabelecimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto do Espaço",
                "verbose_name_plural": "Fotos do Espaço",
            },
        ),
    ]
