# Generated by Django 5.2.5 on 2025-11-21 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estabelecimentos", "0005_alter_estabelecimento_options"),
        ("fotos_espaco", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotosespaco",
            name="estabelecimento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="estabelecimentos.estabelecimento",
            ),
        ),
    ]
