services:
  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    networks:
      - app

  # Serviço da Aplicação Django
  app:
    build: .
    command: sh -c "/wait-for-it.sh db:5432 -- python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
    user: "${UID}:${GID}" 
    networks:
      - app

volumes:
  postgres_data:

networks:
  app: