# Generated by Django 5.2.5 on 2025-11-16 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anuncios", "0001_initial"),
        ("estabelecimentos", "0005_alter_estabelecimento_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anuncio",
            name="estabelecimento",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="estabelecimentos.estabelecimento",
            ),
        ),
    ]
