# Generated by Django 5.2.5 on 2025-10-26 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("estabelecimentos", "0005_alter_estabelecimento_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True)),
                ("imagem", models.ImageField(blank=True, upload_to="produtos/")),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("pontos", models.IntegerField(blank=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "estabelecimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estabelecimentos.estabelecimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
            },
        ),
    ]
