# Generated by Django 5.2.5 on 2025-11-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0002_produto_ativo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="pontos",
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
    ]
