# Generated by Django 5.2.5 on 2025-11-16 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estabelecimentos", "0005_alter_estabelecimento_options"),
        ("produtos", "0003_alter_produto_pontos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="estabelecimento",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="estabelecimentos.estabelecimento",
            ),
        ),
    ]
