# Generated by Django 5.2.5 on 2025-09-25 22:42

import localflavor.br.models
import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_alter_administrador_options_alter_cliente_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrador",
            name="cpf",
            field=localflavor.br.models.BRCPFField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cpf",
            field=localflavor.br.models.BRCPFField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region="BR", unique=True
            ),
        ),
    ]
