# Generated by Django 5.2.5 on 2025-09-27 22:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0004_alter_administrador_cpf_alter_cliente_cpf_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usuario",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
