# Generated by Django 5.2.5 on 2025-10-26 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0005_usuario_created_at_usuario_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="administrador",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="administrador",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="updated_at",
        ),
    ]
