# Generated by Django 5.2.5 on 2025-09-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Estabelecimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("endereco", models.CharField(blank=True, max_length=255, unique=True)),
                ("telefone", models.CharField(blank=True, max_length=15, unique=True)),
                ("descricao", models.TextField(blank=True)),
                ("logotipo", models.ImageField(blank=True, upload_to="logotipos/")),
                (
                    "cnpj",
                    models.CharField(
                        help_text="Formato: 12.345.678/0001-99",
                        max_length=18,
                        unique=True,
                    ),
                ),
                ("horario_funcionamento", models.JSONField(blank=True, default=dict)),
                ("ativo", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
