# Generated by Django 5.2.5 on 2025-09-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estabelecimentos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estabelecimento",
            name="endereco",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="estabelecimento",
            name="telefone",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
