# Generated by Django 5.2.5 on 2025-09-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estabelecimentos", "0002_alter_estabelecimento_endereco_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estabelecimento",
            name="endereco",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="estabelecimento",
            name="telefone",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
