# Generated by Django 5.2.5 on 2025-09-25 22:42

import localflavor.br.models
import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("estabelecimentos", "0003_alter_estabelecimento_endereco_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estabelecimento",
            name="cnpj",
            field=localflavor.br.models.BRCNPJField(
                help_text="Formato: 12.345.678/0001-99", max_length=18, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="estabelecimento",
            name="telefone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region="BR"
            ),
        ),
    ]
