# Generated by Django 5.2.5 on 2025-09-27 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("estabelecimentos", "0004_alter_estabelecimento_cnpj_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="estabelecimento",
            options={
                "verbose_name": "Estabelecimento",
                "verbose_name_plural": "Estabelecimentos",
            },
        ),
    ]
